cmake_minimum_required(VERSION 4.2)
project(CS_300_Project_Two)

set(CMAKE_CXX_STANDARD 14)

add_executable(CS_300_Project_Two
        "CS 300 Project Two CMake Configuration.txt"
        "CS-300-ABCU_Advising_Program_Input.csv"
        "CS 300 Project Two Final Source.cpp"
        "CS 300 Project Two Setup and Testing Guide.md")
